import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-facilities-maintenance-sla-credit-recovery",
  "engine": "recovery",
  "title": "Facilities Maintenance SLA Credit Recovery",
  "shortTitle": "Facilities Maintenance SLA Credit Recovery",
  "tagline": "Calculate and recover service credits for missed response, resolution, uptime, and preventive-maintenance obligations.",
  "industry": "Facilities Cost Recovery",
  "buyer": "Multi-site enterprises and property managers",
  "uiPort": 4722,
  "apiPort": 5722,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Facilities Maintenance SLA Credit Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments in one accountable workflow. Calculate and recover service credits for missed response, resolution, uptime, and preventive-maintenance obligations.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Facilities Maintenance SLA Credit Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("vendor-contract-library","FMS01","Vendor contract library","Execute vendor contract library using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed vendor contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","Vendor contract library Reference","text","FMS01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]}),
feature("location-asset-registry","FMS02","Location asset registry","Execute location asset registry using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed location asset registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","Location asset registry Reference","text","FMS02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]}),
feature("work-order-ingestion","FMS03","Work order ingestion","Execute work order ingestion using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed work order ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","Work order ingestion Reference","text","FMS03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]}),
feature("priority-classification","FMS04","Priority classification","Execute priority classification using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed priority classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","Priority classification Reference","text","FMS04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]}),
feature("response-time-calculation","FMS05","Response time calculation","Execute response time calculation using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed response time calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","Response time calculation Reference","text","FMS05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]}),
feature("resolution-time-calculation","FMS06","Resolution time calculation","Execute resolution time calculation using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed resolution time calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","Resolution time calculation Reference","text","FMS06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]}),
feature("uptime-calculation","FMS07","Uptime calculation","Execute uptime calculation using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed uptime calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","Uptime calculation Reference","text","FMS07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]}),
feature("preventive-maintenance-compliance","FMS08","Preventive maintenance compliance","Execute preventive maintenance compliance using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed preventive maintenance compliance decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","Preventive maintenance compliance Reference","text","FMS08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]}),
feature("repeat-failure-detection","FMS09","Repeat failure detection","Execute repeat failure detection using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed repeat failure detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","Repeat failure detection Reference","text","FMS09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]}),
feature("exclusion-validation","FMS10","Exclusion validation","Execute exclusion validation using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed exclusion validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","Exclusion validation Reference","text","FMS10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]}),
feature("sla-credit-calculation","FMS11","SLA credit calculation","Execute sla credit calculation using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed sla credit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","SLA credit calculation Reference","text","FMS11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]}),
feature("vendor-claim-package","FMS12","Vendor claim package","Execute vendor claim package using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed vendor claim package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","Vendor claim package Reference","text","FMS12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]}),
feature("dispute-workflow","FMS13","Dispute workflow","Execute dispute workflow using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","Dispute workflow Reference","text","FMS13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]}),
feature("invoice-credit-reconciliation","FMS14","Invoice credit reconciliation","Execute invoice credit reconciliation using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed invoice credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","Invoice credit reconciliation Reference","text","FMS14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]}),
feature("location-vendor-analytics","FMS15","Location vendor analytics","Execute location vendor analytics using facilities contracts, assets, work orders, response times, completion evidence, uptime, preventive maintenance, invoices, SLA credits, and payments.","Produce a governed location vendor analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Service Location","text","Vendor / Service Location · Standard Case"],["caseReference","Location vendor analytics Reference","text","FMS15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1593750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1928438],["domainDriver","SLA Measure","select","Response time",["Response time","Resolution time","Asset uptime"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Vendor contract library case","Location asset registry case","Work order ingestion case","Priority classification case","Response time calculation case"]})
]);
